/**
 * Ids renamed over time (v2.3.0 to follow the English names, then card renames). Saves written before keep the old ones and are mapped on load:
 * only what saves hold (cards in decks and in the handbook, their perks, enemies on the map and in the handbook).
 */
const was = (m: Record<string, string>): Map<string, string> => new Map(Object.entries(m));

const CARDS = was({
  arcaneBolt: 'clippy',
  arcaneEcho: 'echoChamber',
  arcaneMemo: 'clippy',
  arcaneMissiles: 'replyAll',
  bandage: 'macGyver',
  bash: 'wrenchWhack',
  battleCry: 'bellaCiao',
  blackDeath: 'blackFriday',
  blightBurst: 'toxicLeak',
  blizzard: 'officeAC',
  bloodletting: 'doubleShift',
  bloodthirst: 'backPay',
  bomb: 'deadline',
  boneSpike: 'skeletonCrew',
  boneWall: 'barricade',
  bulwark: 'safetyRegs',
  busyHands: 'spaghettiCode',
  cache: 'clearCache',
  cleave: 'crowbar',
  coffeeBreak: 'fika',
  combustion: 'meltdown',
  contagion: 'wordOfMouth',
  copyPaste: 'ctrlCCtrlV',
  counterstrike: 'grievance',
  daggerThrow: 'redStapler',
  deathCoil: 'deadLetter',
  defend: 'bobTheBuilder',
  doubleEspresso: 'italianEspresso',
  drainLife: 'bloodMoney',
  ductTape: 'macGyver',
  earthshaker: 'hydraulicPress',
  epidemic: 'walkout',
  evocation: 'powerNap',
  execute: 'justCause',
  festeringStrike: 'sickLeave',
  fireball: 'slagBall',
  fireFlask: 'molotov',
  flurry: 'spaghettiCode',
  frailty: 'snowden',
  frostArmor: 'coldStorage',
  frostbolt: 'coldCall',
  ghoulBite: 'zombieShift',
  graveWard: 'karlMarx',
  hardHat: 'bobTheBuilder',
  healingPotion: 'firstAidKit',
  heavyBlow: 'sledgehammer',
  hex: 'writeUp',
  iceLance: 'coldShoulder',
  ignite: 'burnout',
  improvementPlan: 'tpsReport',
  ironWall: 'wallStreet',
  juggernaut: 'forklift',
  leech: 'mandatoryFun',
  lunchBreak: 'secondBreakfast',
  machineDown: 'pcLoadLetter',
  manaGeode: 'italianEspresso',
  manaPotion: 'energyDrink',
  manaShard: 'coffee',
  manaSurge: 'caffeineJolt',
  mealVoucher: 'mangioni',
  mirrorImage: 'lookBusy',
  movingBox: 'dunderMifflinBox',
  noxiousCloud: 'chainSmoking',
  palletWall: 'wallStreet',
  parry: 'youShallNotPass',
  pip: 'tpsReport',
  plague: 'sabotage',
  polymorph: 'metamorphosis',
  previousEmail: 'asPerMyLastEmail',
  pushback: 'youShallNotPass',
  pyroblast: 'blastFurnace',
  quickFavour: 'godfathersFavour',
  rampage: 'stonks',
  redTape: 'papersPlease',
  rehire: 'sisyphus',
  rivetGun: 'releaseTheHounds',
  rot: 'rust',
  secondWind: 'secondBreakfast',
  shatter: 'blueScreen',
  shieldBash: 'shoulderCheck',
  siphonRot: 'mangioni',
  slime: 'drama',
  smokeBomb: 'fireDrill',
  smokestack: 'chainSmoking',
  solidarity: 'karlMarx',
  spamFilter: 'nigerianPrince',
  spark: 'staticShock',
  strike: 'punch',
  takeCredit: 'mrBurnsEmpire',
  tenure: 'employeeOfTheMonth',
  timeSlip: 'modernTimes',
  toxicDart: 'toxicMemo',
  toxin: 'gossip',
  unbreakable: 'employeeOfTheMonth',
  unionChant: 'bellaCiao',
  virulentForm: 'classStruggle',
  ward: 'fireDoor',
  warDrums: 'picketDrums',
  whirlwind: 'declareBankruptcy',
  whistleblow: 'snowden',
  windUpIntern: 'mrRoboto',
  wither: 'slowdown',
  workaholic: 'stakhanov',
  workLife: 'workLifeBalance',
});
const ENEMIES = was({
  boneKnight: 'securityMonitor',
  cobot: 'replacement',
  compliance: 'complianceOfficer',
  cultist: 'teamLeader',
  goblin: 'goblinConsultant',
  happiness: 'happinessOfficer',
  hr: 'hrBitch',
  hrVideo: 'hrOrientationVideo',
  janitor: 'nightJanitor',
  lich: 'slavesCeo',
  meticulous: 'meticulousColleague',
  phoneTree: 'switchboard',
  rat: 'snitch',
  skeleton: 'seniorBoomer',
  sleeper: 'guyAsleep',
  slime: 'toxicCoworker',
  wellness: 'wellnessCoach',
});
const PERKS = was({ innate: 'fastTrack', discount: 'budgetCut' });

/** Old id → new id, by kind (the content test checks every new id exists). */
export const RENAMED = { cards: CARDS, enemies: ENEMIES, perks: PERKS };

export const renamedCard = (id: string): string => CARDS.get(id) ?? id;
export const renamedEnemy = (id: string): string => ENEMIES.get(id) ?? id;
export const renamedPerk = (id: string): string => PERKS.get(id) ?? id;
