/**
 * Ids renamed to follow the English names (v2.3.0). Saves written before keep the old ones and are mapped on load:
 * only what saves hold (cards in decks and in the handbook, their perks, enemies on the map and in the handbook).
 */
const was = (m: Record<string, string>): Map<string, string> => new Map(Object.entries(m));

const CARDS = was({
  arcaneBolt: 'arcaneMemo',
  arcaneEcho: 'echoChamber',
  arcaneMissiles: 'replyAll',
  bandage: 'ductTape',
  bash: 'wrenchWhack',
  battleCry: 'unionChant',
  blackDeath: 'blackFriday',
  blightBurst: 'toxicLeak',
  blizzard: 'officeAC',
  bloodletting: 'doubleShift',
  bloodthirst: 'backPay',
  bomb: 'deadline',
  boneSpike: 'skeletonCrew',
  boneWall: 'barricade',
  bulwark: 'safetyRegs',
  cleave: 'crowbar',
  combustion: 'meltdown',
  contagion: 'wordOfMouth',
  counterstrike: 'grievance',
  daggerThrow: 'redStapler',
  deathCoil: 'deadLetter',
  defend: 'hardHat',
  drainLife: 'bloodMoney',
  earthshaker: 'hydraulicPress',
  epidemic: 'walkout',
  evocation: 'powerNap',
  execute: 'justCause',
  festeringStrike: 'sickLeave',
  fireFlask: 'molotov',
  fireball: 'slagBall',
  flurry: 'busyHands',
  frailty: 'whistleblow',
  frostArmor: 'coldStorage',
  frostbolt: 'coldCall',
  ghoulBite: 'zombieShift',
  graveWard: 'solidarity',
  healingPotion: 'firstAidKit',
  heavyBlow: 'sledgehammer',
  hex: 'writeUp',
  iceLance: 'coldShoulder',
  ignite: 'burnout',
  ironWall: 'palletWall',
  juggernaut: 'forklift',
  leech: 'mandatoryFun',
  manaGeode: 'doubleEspresso',
  manaPotion: 'energyDrink',
  manaShard: 'coffee',
  manaSurge: 'caffeineJolt',
  mirrorImage: 'lookBusy',
  noxiousCloud: 'smokestack',
  parry: 'pushback',
  pip: 'improvementPlan',
  plague: 'sabotage',
  polymorph: 'metamorphosis',
  pyroblast: 'blastFurnace',
  rampage: 'stonks',
  rot: 'rust',
  secondWind: 'lunchBreak',
  shatter: 'blueScreen',
  shieldBash: 'shoulderCheck',
  siphonRot: 'mealVoucher',
  slime: 'drama',
  smokeBomb: 'fireDrill',
  spark: 'staticShock',
  strike: 'punch',
  timeSlip: 'modernTimes',
  toxicDart: 'toxicMemo',
  toxin: 'gossip',
  unbreakable: 'tenure',
  virulentForm: 'classStruggle',
  warDrums: 'picketDrums',
  ward: 'fireDoor',
  whirlwind: 'declareBankruptcy',
  wither: 'slowdown',
  workLife: 'workLifeBalance',
});
const ENEMIES = was({
  boneKnight: 'securityMonitor',
  compliance: 'complianceOfficer',
  cultist: 'teamLeader',
  goblin: 'goblinConsultant',
  happiness: 'happinessOfficer',
  hr: 'hrBitch',
  hrVideo: 'hrOrientationVideo',
  janitor: 'nightJanitor',
  lich: 'slavesCeo',
  meticulous: 'meticulousColleague',
  rat: 'snitch',
  skeleton: 'seniorBoomer',
  sleeper: 'guyAsleep',
  slime: 'toxicCoworker',
  wellness: 'wellnessCoach',
});
const PERKS = was({ innate: 'fastTrack', discount: 'budgetCut' });

/** Old id → new id, by kind (the content test checks every new id exists). */
export const RENAMED = { cards: CARDS, enemies: ENEMIES, perks: PERKS };

export const renamedCard = (id: string): string => CARDS.get(id) ?? id;
export const renamedEnemy = (id: string): string => ENEMIES.get(id) ?? id;
export const renamedPerk = (id: string): string => PERKS.get(id) ?? id;
